# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suma_resta_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#from python_qt_binding import QtGui, QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img1_lbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1_lbl.sizePolicy().hasHeightForWidth())
        self.img1_lbl.setSizePolicy(sizePolicy)
        self.img1_lbl.setMinimumSize(QtCore.QSize(0, 300))
        self.img1_lbl.setText("")
        self.img1_lbl.setObjectName("img1_lbl")
        self.verticalLayout_2.addWidget(self.img1_lbl)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.img1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.img1_btn.setObjectName("img1_btn")
        self.horizontalLayout_3.addWidget(self.img1_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img2_lbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img2_lbl.sizePolicy().hasHeightForWidth())
        self.img2_lbl.setSizePolicy(sizePolicy)
        self.img2_lbl.setMinimumSize(QtCore.QSize(0, 300))
        self.img2_lbl.setText("")
        self.img2_lbl.setObjectName("img2_lbl")
        self.verticalLayout_3.addWidget(self.img2_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.img2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.img2_btn.setObjectName("img2_btn")
        self.horizontalLayout_4.addWidget(self.img2_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.img3_lbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img3_lbl.sizePolicy().hasHeightForWidth())
        self.img3_lbl.setSizePolicy(sizePolicy)
        self.img3_lbl.setMinimumSize(QtCore.QSize(0, 200))
        self.img3_lbl.setText("")
        self.img3_lbl.setObjectName("img3_lbl")
        self.verticalLayout.addWidget(self.img3_lbl)
        self.operacion_lbl = QtWidgets.QLabel(self.centralwidget)
        self.operacion_lbl.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operacion_lbl.sizePolicy().hasHeightForWidth())
        self.operacion_lbl.setSizePolicy(sizePolicy)
        self.operacion_lbl.setMinimumSize(QtCore.QSize(0, 0))
        self.operacion_lbl.setObjectName("operacion_lbl")
        self.verticalLayout.addWidget(self.operacion_lbl)
        self.operacion_cb = QtWidgets.QComboBox(self.centralwidget)
        self.operacion_cb.setObjectName("operacion_cb")
        self.operacion_cb.addItem("")
        self.operacion_cb.addItem("")
        self.operacion_cb.addItem("")
        self.operacion_cb.addItem("")
        self.verticalLayout.addWidget(self.operacion_cb)
        self.formato_lbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formato_lbl.sizePolicy().hasHeightForWidth())
        self.formato_lbl.setSizePolicy(sizePolicy)
        self.formato_lbl.setObjectName("formato_lbl")
        self.verticalLayout.addWidget(self.formato_lbl)
        self.formato_cb = QtWidgets.QComboBox(self.centralwidget)
        self.formato_cb.setObjectName("formato_cb")
        self.formato_cb.addItem("")
        self.formato_cb.addItem("")
        self.formato_cb.addItem("")
        self.verticalLayout.addWidget(self.formato_cb)
        self.img3_btn = QtWidgets.QPushButton(self.centralwidget)
        self.img3_btn.setObjectName("img3_btn")
        self.verticalLayout.addWidget(self.img3_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.img1_btn.setText(_translate("MainWindow", "Cargar imagen 1"))
        self.img2_btn.setText(_translate("MainWindow", "Cargar imagen 2"))
        self.operacion_lbl.setText(_translate("MainWindow", "Operación:"))
        self.operacion_cb.setItemText(0, _translate("MainWindow", "Suma"))
        self.operacion_cb.setItemText(1, _translate("MainWindow", "Resta"))
        self.operacion_cb.setItemText(2, _translate("MainWindow", "If lighter"))
        self.operacion_cb.setItemText(3, _translate("MainWindow", "If darker"))
        self.formato_lbl.setText(_translate("MainWindow", "Formato:"))
        self.formato_cb.setItemText(0, _translate("MainWindow", "RGB promediado"))
        self.formato_cb.setItemText(1, _translate("MainWindow", "RGB clampeado"))
        self.formato_cb.setItemText(2, _translate("MainWindow", "YIQ clampeado"))
        self.img3_btn.setText(_translate("MainWindow", "Procesar"))


def main():
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    """
    
    img1_pixmap = QtGui.QPixmap("lena512.png")
    #img1_pixmap = img1_pixmap.scaled(ui.img1_lbl.size(), QtCore.Qt.KeepAspectRatio)
    ui.img1_lbl.setScaledContents(True)    
    ui.img1_lbl.setSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
    ui.img1_lbl.setPixmap(img1_pixmap)
    ui.img1_lbl.show()

    
    ui.img1_lbl.setScaledContents(True)    
    ui.img1_lbl.setSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
    
    
    
    img2_pixmap = QtGui.QPixmap("baboon.png")
    #img2_pixmap = img2_pixmap.scaled(ui.img2_lbl.size(), QtCore.Qt.KeepAspectRatio)     
    ui.img2_lbl.setScaledContents(True)    
    ui.img2_lbl.setSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
    ui.img2_lbl.setPixmap(img2_pixmap)
    ui.img2_lbl.show()
        
    """
    MainWindow.show()
    sys.exit(app.exec_())    

if __name__ == "__main__":
    main()

